import Head from 'next/head'
import Image from 'next/image'
import Avatar from "../components/Avatar/Avatar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MyGoogle</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>

          {/*Icon*/}

          <Avatar url="https://i02.fotocdn.net/s126/ea543fdc0afcb043/gallery_xs/2872578917.jpg"/>
        </div>
      </header>

      {/*body*/}

      {/*footer*/}

    </div>
  )
}
