import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>MyGoogle</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      {/*header*/}

      {/*body*/}

      {/*footer*/}

      <h1 className='p-10'>lets build google!</h1>

    </div>
  )
}
